version: "3"
networks:
  app-tier:
    driver: bridge

services:
  app:
    image: laravel-www
    container_name: bot-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mysql
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 8080:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app

  scheduler:
    image: laravel-www
    container_name: bot-scheduler
    depends_on:
      - app
      - redis
      - mysql
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    environment:
      CONTAINER_ROLE: scheduler
      APP_ENV: local

  queue:
    image: laravel-www
    container_name: bot-queue
    depends_on:
      - app
      - redis
      - mysql
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    environment:
      CONTAINER_ROLE: queue
      APP_ENV: local

  redis:
    container_name: bot-redis
    image: redis:4-alpine
    networks:
      - app-tier
    ports:
      - 16379:6379
    volumes:
      - redis:/data

  mysql:
    container_name: bot-mysql
    image: mysql:5.7
    networks:
      - app-tier
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  minio:
    container_name: bot-minio
    image: minio/minio
    networks:
      - app-tier
    volumes:
      - ./storage/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    command: server --address 0.0.0.0:9000 /data

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"
  data3-1:
    driver: "local"
  data3-2:
    driver: "local"
